name: Baseline PR Comment
on:
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: read
  pull-requests: write
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm --workspace packages/baseline-core run build
      - run: npm --workspace packages/baseline-cli run build
      - run: node packages/baseline-cli/dist/index.js scan --path . --report md --out baseline.md --use-browserslist
      - name: Find or create comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: baseline.md